name: Publish NPM Package
 
on:
  # push:
  #   branches:
  #     - main  # Change this to the branch you want to publish from
  workflow_dispatch:
 
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
 
    steps:
      - uses: actions/checkout@v4
 
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/20'  # Adjust for the version your project needs
          registry-url: 'https://npm.pkg.github.com/'
 
      - name: Install dependencies
        run: npm install
 
      - name: Build package
        run: npm run build
 
      - name: Publish to GitHub Packages Registry
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
